<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rmschannels [
  <!ELEMENT rmschannels (channel+)>

  <!ELEMENT channel (basecall, callsign, password, gridsquare, frequency, mode,
		     autoonly, baud, power, height, gain, direction, hours,
		     groupreference, servicecode, statuschecker)>
    <!ATTLIST channel name CDATA #REQUIRED>
    <!ATTLIST channel type CDATA #REQUIRED>
    <!ATTLIST channel active CDATA #REQUIRED>

  <!ELEMENT basecall (#PCDATA)>
  <!ELEMENT callsign (#PCDATA)>
  <!ELEMENT password (#PCDATA)>
  <!ELEMENT gridsquare (#PCDATA)>
  <!ELEMENT frequency (#PCDATA)>
  <!ELEMENT mode (#PCDATA)>
  <!ELEMENT autoonly (#PCDATA)>
  <!ELEMENT baud (#PCDATA)>
  <!ELEMENT power (#PCDATA)>
  <!ELEMENT height (#PCDATA)>
  <!ELEMENT gain (#PCDATA)>
  <!ELEMENT direction (#PCDATA)>
  <!ELEMENT hours (#PCDATA)>
  <!ELEMENT groupreference (#PCDATA)>
  <!ELEMENT servicecode (#PCDATA)>
  <!ELEMENT statuschecker (#PCDATA)>
]>
<rmschannels>
  <channel name="radio" type="ax25" active="yes">
    <basecall>N0CALL</basecall>
    <callsign>N0CALL-10</callsign>
    <password>password</password>
    <gridsquare>AA00AA</gridsquare>
    <frequency>144000000</frequency>
    <mode>0</mode>
    <autoonly>0</autoonly>
    <baud>1200</baud>
    <power>50</power>
    <height>10</height>
    <gain>0</gain>
    <direction>0</direction>
    <hours>24/7</hours>
    <groupreference>1</groupreference>
    <servicecode>PUBLIC</servicecode>
    <statuschecker>
      /usr/local/bin/rmschanstat $type $name $callsign
    </statuschecker>
  </channel>
</rmschannels>
